apiVersion: apps/v1 
kind: Deployment
metadata:
  name: cowsay-deployment
  namespace: kurenkov-miklos
  labels:
    app: cowsay-hw
spec:
  selector:
    matchLabels:
      app: cowsay-hw
  replicas: 1
  template:
    metadata:
      labels:
        app: cowsay-hw
    spec:
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-pvc-with-blackjack
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      - name: cowsay
        image: hsnlabhu/hw2:cowsay
        volumeMounts:
        - name: shared-data
          mountPath: /root/html
