apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc-with-blackjack
  namespace: kurenkov-miklos
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
