apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-with-blackjack-and-hookers
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
